### ISSUE TITLE
[Issue]:  can delete a entry when we type all small case 'delete' instead of the 'Delete'

### ISSUE THREAD

**Issue by antsand** [bcgov/PIMS#2526] opened 2024-07-11 20:21 UTC
### Details

![image](https://github.com/bcgov/PIMS/assets/8980101/46779a6f-902a-4ecc-a1b2-3b1641ed0dbf)

Try to delete a property and type lower case delete. IT will delete the entry.

### Issue Type

Visual

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you using?

Windows

### Environment (Optional)

None

**Comment by GrahamS-Quartech** [comment] 2024-07-23 20:12
Confirmed with PO that this behavior is intended. Closing as won't fix.

**Closed by GrahamS-Quartech** 2024-07-23 20:12 UTC
