### ISSUE TITLE
[Issue]: No verification when changing postal code on edit property dialog

### ISSUE THREAD

**Issue by antsand** [bcgov/PIMS#2525] opened 2024-07-11 20:16 UTC
### Details

![image](https://github.com/bcgov/PIMS/assets/8980101/a4c9415e-9e1d-4bcf-9c91-a63b4c79ff3e)

If someone enters the wrong address like the wrong postal code they system is not able to catch the mis-match in the address. 

### Steps to Reproduce (Optional)

go to the parcel info page and try to edit the address. Put any random postal code and the system will accept the postal code without any verification. 

### Issue Type

Visual

### What browsers are you seeing the problem on?

Firefox

### What Operating System are you using?

Windows

### Environment (Optional)

None

**Comment by GrahamS-Quartech** [comment] 2024-07-15 20:03
@antsand 
If the issue is just that the postal code is not checked against what is entered in the address field, this will likely be marked as Won't Fix, as we do not really use the postal code as a source of truth anywhere in the application. It is more important that the address is valid.

**Closed** 2024-07-22 21:34 UTC
